### ISSUE TITLE
Query: EH1 alpha release

### ISSUE THREAD

**Issue by tommy-gilligan** [rust-embedded/embedded-hal-mock#70]
Thank you for having a EH1 alpha branch that is up-to-date with the latest EH1 alpha.  It has been very useful in some work I've been doing.
I think it would be nice to release this work soon (perhaps a version of embedded-hal-mock that supports both EH0.2 and EH1.0-alpha).  I'm happy to sync the branch with main if that is at all helpful but also totally understand if a merge is not planned for anytime soon.  I would love to know your thoughts on this.

**Comment by newAM** [comment]
I had the same thought (merging eh0.2 and eh1a into the same branch).  Even after eh1 is released 0.2 will be around a long time and it would be nice to support both in this crate.

I'm also happy to help out with merge work to make this happen.

**Comment by ryankurte** [comment]
yeah supporting both is an interesting question... it's always in need of updates but, is this something we can support just by keeping `e-h-m` against alpha then either recommending or pulling in https://github.com/ryankurte/embedded-hal-compat ?

**Comment by newAM** [comment]
I envision this being two separate implementations for each HAL.  For exmaple, I have an eh0 and an eh1 module in my W5500 crate: https://github.com/newAM/w5500-rs/tree/main/ll/src

**Comment by rursprung** [comment]
having a release of the mock implementation for e-h 1.0.0-alpha.10 would be very useful as i'd like to add support for it to my crates but i need the mock implementations for CI.

is there any chance to create a corresponding alpha release off of the alpha branch for now?

IMHO going forward merging the two together would be easiest, as is also done by the HAL implementations (e.g. [stm32f4xx-hal](https://github.com/stm32-rs/stm32f4xx-hal) is doing it like this)
